service: serverless-${env:AWS_ENV}

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  region: us-east-1

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: time-${env:AWS_ENV}.celidor.uk
    basePath: ${env:AWS_STAGE}
    stage: ${env:AWS_STAGE}
    createRoute53Record: true
    endpointType: 'regional'
